---
apiVersion: infrahub.app/v1
kind: Object
spec:
  kind: NetworkDevice
  data:
    - name: edge-ams-01
      description: Edge router, Amsterdam
      member_of_groups:
        - ["edge_routers"]
      interfaces:
        kind: NetworkInterface
        data:
          - name: Ethernet1
            description: Uplink to core-ams-01
          - name: Ethernet2
    - name: edge-par-01
      description: Edge router, Paris
      member_of_groups:
        - ["edge_routers"]
      interfaces:
        kind: NetworkInterface
        data:
          - name: Ethernet1
            description: Uplink to core-par-01
